spring:
  # KAKAO
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: vi2ZsxV43twrli7TYqBb
            client-secret: zpatnxDwD9
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope: name, email, mobile
            client-name: Naver

          kakao:
            authorization-grant-type: authorization_code
            client-id: client_id
            client-secret: client_pw
            scope: profile, account_email
            client-authentication-method: POST
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-name: kakao

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

          kakao:
            token-uri: https://kauth.kakao.com/oauth/token
            user-name-attribute: 'id'
            user-info-uri: https://kapi.kakao.com/v2/user/me
            authorization-uri: https://kauth.kakao.com/oauth/authorize