server:
    port: 8080

spring:
    data:
        web:
            pageable:
                default-page-size: 10
                max-page-size: 100

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/sssgssagDB?serverTimezone=Asia/Seoul
        username: root
        password: 1234

    jpa:
        generate-ddl: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                show_sql: true
        show_sql: false
        database: mysql
        hibernate:
            ddl-auto: update

    servlet:
        multipart:
            max-file-size: 50MB  #최대 파일 사이즈를 50MB로 지정
            max-request-size: 500MB

    security:
        oauth2:
            client:
                registration:
                    naver:
                        client-id: [Client Id 입력]
                        client-secret: [Secret Key 입력]
                        redirect-uri: "http://13.209.26.150:9000/login/oauth2/code/naver"
                        authorization-grant-type: authorization_code
                        scope: name, email, mobile
                        client-name: Naver

                    kakao:
                        authorization-grant-type: authorization_code
                        client-id: [Client Id 입력]
                        client-secret: [Secret Key 입력]
                        scope: profile_nickname, account_email
                        client-authentication-method: POST
                        redirect-uri: "http://13.209.26.150:9000/login/oauth2/code/kakao"
                        client-name: kakao

                provider:
                    naver:
                        authorization_uri: https://nid.naver.com/oauth2.0/authorize
                        token_uri: https://nid.naver.com/oauth2.0/token
                        user-info-uri: https://openapi.naver.com/v1/nid/me
                        user_name_attribute: response

                    kakao:
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-name-attribute: 'id'
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        authorization-uri: https://kauth.kakao.com/oauth/authorize

cloud:
    aws:
        credentials:
            accessKey: [Access Key 입력]
            secretKey: [Secret Key 입력]
        s3:
            bucket: ssg-ssag-bucket
        region:
            static: ap-northeast-2
        stack:
            auto: false

jwt:
    tokenValidTime: 1800000

    secret: [Secret Key 입력]

sms:
    serviceId: ncp:sms:kr:265220930008:ssgssag
    accessKey: [Access Key 입력]
    secretKey: [Secret Key 입력]
    phone: '01047569038'